shared: 
  - source: ./render/math.js
    target: math.js   # will surface as apps://extendo-render/math.js
internal:
  - source: ./render/mermaid/code.js
installed:
  - source: ./render/mermaid/extension.yaml
    target: render/github/mermaid/extension.yaml


