shared: 
  - actual: ./math/dist/index.js
    logical: math   # will surface as apps://extendo-render/math
internal:
  - actual: docker://extendo-render:mermaid
    logical: mermaid   # will surface as apps://extendo-render/mermaid for reference internally
    commandLine: node /mermaid.js
installed:
  - actual: ./mermaid/extension.yaml
    logical: render/github/mermaid/extension.yaml
