name: extendo-api
description: Set of interesting App API samples
application:
  visibility: universe
  permissions:
    contents: read
    metadata: read
  content:
    installed:
      - actual: ../../../api/getHandler.js
        logical: api/extendo-api/get.js
      - actual: ../../../api/postHandler.js
        logical: api/extendo-api/post.js
        