name: extendo-render
description: Amazing set of rendering capabilities for content on GitHub 
application:
  visibility: universe
  permissions:
    contents: read
    metadata: read
  content:
    shared: 
      - actual: qotd.js   # expose a random quote of the day 
        logical: qotd   # will surface as apps://extendo-render/qotd
    internal:
      - actual: image://jeffmcaffer/jupyter:1
        logical: jupyter   # will surface as apps://extendo-render/jupyter for reference internally
    installed:
      - actual: ../../../jupyter/extension.yaml
        logical: render/github/ipynb.yaml
        