name: extendo-render
description: Amazing set of rendering capabilities for content on GitHub 
application:
  visibility: universe
  permissions:
    contents: read
    metadata: read
  content:
    shared: 
      - actual: ../../../math/dist/index.js
        logical: math   # will surface as apps://extendo-render/math
    internal:
      - actual: image://jeffmcaffer/mermaid:1
        logical: mermaid   # will surface as apps://extendo-render/mermaid for reference internally
      - actual: image://jeffmcaffer/jupyter:1
        logical: jupyter   # will surface as apps://extendo-render/jupyter for reference internally
    installed:
      - actual: ../../../api/getHandler.js
        logical: api/extendo-render/get.js
      - actual: ../../../mermaid/extension.yaml
        logical: render/github/mermaid/extension.yaml
      - actual: ../../../jupyter/extension.yaml
        logical: render/github/ipynb.yaml
